name: Go Build

on:
  push:
    branches:
      - main
  tags:
    - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'  # Asegúrate de que coincida con la versión de Go en tu proyecto

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o passgenie ./cmd/passgenie

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # Cambia esto a una versión que quieras etiquetar
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./passgenie
          asset_name: passgenie
          asset_content_type: application/octet-stream
