name: Build and Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, e.g., v1.0, v20.15.10

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Actualizado a la versión v3

      - name: Set up Go
        uses: actions/setup-go@v3 # Actualizado a la versión v3
        with:
          go-version: '1.20'

      - name: Build
        run: go build -o passgenie ./cmd/passgenie

      - name: Test
        run: go test -v ./...

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Build and release of version ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./passgenie
          asset_name: passgenie
          asset_content_type: application/octet-stream
