name: Build and Package Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, e.g., v1.0, v20.15.10

jobs:
  build:
    name: Build and Package Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o passgenie-linux ./cmd/passgenie

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o passgenie-windows.exe ./cmd/passgenie

      - name: Package binaries into a ZIP file
        run: |
          zip passgenie-release.zip passgenie-linux passgenie-windows.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Build and release of version ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload ZIP Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./passgenie-release.zip
          asset_name: passgenie-release.zip
          asset_content_type: application/zip
